name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

jobs:
  release:
    name: Release
    uses: ./.github/workflows/single_release.yml
    with:
      version: ${{ inputs.version }}
      modrinth: true
      curseforge: true
      github: true
    secrets: inherit
